
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vireachavefinanceira
  password: nash270292
  host: localhost
  port: 5432

development:
  <<: *default
  database: octoevents_development

test:
  <<: *default
  database: octoevents_test


production:
  <<: *default
  database: octoevents_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
